[package]
name = "aurora"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.100"
iced = { version = "0.13.1", features = ["canvas", "tokio"] }
serde = "1.0.228"
serde_json = "1.0.145"
tokio = "1.48.0"
uuid = { version = "1.18.1", features = ["serde"] }
